spring:
  config:
    activate:
      on-profile: uat

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.msa.userapp: INFO
    software.amazon.awssdk: WARN
    org.apache.http: WARN
